on:
  push:
    branches:
      [main, spare]
      # - main

name: Test & Heroku Deployment
jobs:
  test:
    needs: [check_skip_flags]
    if: "!contains(needs.check_skip_flags.outputs.head-commit-message, '[skip-test]')"
    uses: ./.github/workflows/test.yml
    with:
      os: "['ubuntu-latest', 'macos-latest', 'windows-latest']"
    secrets: inherit
  heroku:
    runs-on: ubuntu-latest
    needs: test
    # if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.13
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "fairhive-pixelart"
          heroku_email: "jsie@fairhive-labs.com"
          usedocker: true
          healthcheck: "https://fairhive-pixelart.herokuapp.com/health"
          checkstring: "ok"
          delay: 5
          rollbackonhealthcheckfailed: true
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: _github
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: "https://fairhive-pixelart.herokuapp.com/"
          SLACK_TITLE: Heroku Deployment - pixelart
          SLACK_USERNAME: _whyvrafvr
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
